### ISSUE TITLE
13寸MBPReset按钮被CPI Curve挡住了一部分

### ISSUE THREAD

**Issue by erichuang1994** [quietshu/y86#1]
OTZ戍爷超强

**Comment by shuding** [comment]
咦，我这儿（非 Retina OS X，Chrome & Safari & FireFox）没办法重现这个 issue。不知道是否因为浏览器缩放，或者别的问题……`_(:з」∠)_`

求截图或测试环境。

**Comment by erichuang1994** [comment]
[截图](https://cloud.githubusercontent.com/assets/8861265/8143227/98db2ac6-11d4-11e5-97cc-5b29dfa820b9.png)来了

**Comment by taineleau-zz** [comment]
应该是retina的锅。
retina下chrome情况如上。
safari，直接挂了，cf. http://www.douban.com/photos/photo/2249807275/
firefox没问题。

**Comment by shuding** [comment]
谢谢 @taineleau ，萌萌的图床。看来我暂时没法 debug 了……。
